### ISSUE TITLE
Do you need extra Broadcom 94352z WiFi Bluetooth card to enable Airdrop? Is it big sur enabled?

### ISSUE THREAD

**Issue by cyrusauyeungc** [YucongDing/Ryzen-3900X-Hackintosh#1]
This build looks amazing! However I’d like to know if there are anything not working at the moment. And would it support big sur too? Thanks.

**Comment by LurnD** [comment]
Yep, you should inject BCM Kext to it. you may also search DW1560 for the kext too. But when I used bcm94352z in my laptop, there is many problem like losing BT when wake the system, slowly connected to AirPods/AirPods Pro/Keyboard and sometimes you may won't search any contacts while using Airdrop.
If you want to use airdrop, I recommend you to use dw1860a or apple's wireless cards, it fits PC very well and don't need any modification.
I haven't test Big Sur yet, this machine is running on datacenter in my school, but I am on a winter holiday lol. I am using a hades canyon(intel nut) with Lenovo DW1860A at home, the card works really well.

**Comment by cyrusauyeungc** [comment]
thank you very much and appreciate that :)!
